### PR TITLE
throw exception when bag files aren't there

### PR DESCRIPTION
**Pull request by bonniegee**
This is not specifically tested--the only way I could think to easily test this would be to create a new TestCase which seemed like overkill but may be fine?

### CODE REVIEW

**Comment by helrond** [comment]
Couldn't you just delete whatever is in the src_dir prior to running tests?

**Comment by bonniegee** [comment]
> Couldn't you just delete whatever is in the src_dir prior to running tests?

But then wouldn't I need to add things back to the src_dir for the other tests in that TestCase?

**Comment by helrond** [comment]
No, because all of that is happening in the `setUp` method, which runs before each method that starts with `test_`.

**Comment by bonniegee** [comment]
> No, because all of that is happening in the `setUp` method, which runs before each method that starts with `test_`.

🤦‍♀️

I have implemented that change, but I'm still getting inconsistent view test failures so I'm still working on fixing #156.

**Review by helrond — APPROVED** [review]
Yup, looks right to me!

**Pull request merged**
